name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Le pipeline sera déclenché lorsque vous poussez sur la branche `main`

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest  # Le job sera exécuté sur un runner Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v4  # Cloner le code depuis votre dépôt

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Installer Node.js
        with:
          node-version: '14'  # Choisir la version de Node.js à utiliser

      - name: Install dependencies
        run: npm install  # Installer les dépendances

      - name: Run tests
        run: npm test  # Exécuter les tests définis dans votre projet

      - name: Build application
        run: npm run build  # Lancer le script de build (exemple : afficher un message)

      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }} # Récupérer le webhook Discord depuis les secrets
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has build succesfully.'

  # Job de déploiement sur Staging
  deploy_staging:
    runs-on: ubuntu-latest
    needs: build  # Ce job ne s'exécutera que si le job de build réussit

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run: |
          echo "Déploiement sur Staging..."
          # Remplacer cette commande par celle qui déploie sur votre environnement de staging
          # Par exemple, une commande SCP, ou un script de déploiement

  # Job de déploiement en Production
  deploy_production:
    runs-on: ubuntu-latest
    needs: deploy_staging  # Ce job ne s'exécutera que si le job de staging réussit

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          echo "Déploiement en Production..."
          # Remplacer cette commande par celle qui déploie sur votre environnement de production
          # Par exemple, une commande SCP, ou un script de déploiement
